import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NextAuthSessionProvider from "../providers/sessionProvider";
import "./globals.css";

const PoppinsFont = Poppins({ weight:["400", "800"], subsets:["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: "noindex, nofollow",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={PoppinsFont.className}>
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
